from enum import Enum

from pydantic import BaseModel


class Intent(str, Enum):

    BOOKING_STATUS = "BOOKING_STATUS"

    BUS_DELAY = "BUS_DELAY"

    BUS_TRACKING = "BUS_TRACKING"

    BOOKING_CANCEL = "BOOKING_CANCEL"

    REFUND_STATUS = "REFUND_STATUS"

    PAYMENT_ISSUE = "PAYMENT_ISSUE"

    RESCHEDULE = "RESCHEDULE"

    LIST_BOOKINGS = "LIST_BOOKINGS"

    COMPLAINT = "COMPLAINT"

    FAQ = "FAQ"

    PROVIDE_BOOKING_CODE = "PROVIDE_BOOKING_CODE"

    FOLLOW_UP = "FOLLOW_UP"

    CREATE_BOOKING = "CREATE_BOOKING"

    GENERAL = "GENERAL"


class IntentResult(BaseModel):

    intent: Intent